name: Build | Ethereum | TickenEvent
on:
  push:
    branches:
      - main
    paths:
      - "ethereum/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          path: main

      - name: "Checkout PUBBC Connector"
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TICKEN_PUBBC_CONNECTOR_UPDATE_TOKEN }}
          repository: ticken-ts/ticken-pubbc-connector
          path: ticken-pubbc-connector

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18"

      - name: Install Dependencies
        working-directory: ./main/ethereum
        run: npm install

      - name: Build Smart Contract
        working-directory: ./main/ethereum
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: eth-ticken-event
          path: ./main/ethereum/build/contracts/TickenEvent.json

      - name: Copy Contract ABI to Repository
        run: |
          rm ./ticken-pubbc-connector/eth-connector/TickenEvent.json

          cp \
            ./main/ethereum/build/contracts/TickenEvent.json  \
            ./ticken-pubbc-connector/eth-connector/TickenEvent.json

          cd ./ticken-pubbc-connector

          git config --global user.email "ftorraca@fi.uba.ar"
          git config --global user.name  "facundotorraca"

          git add ./eth-connector/TickenEvent.json
          git commit -m "automatic ticket commit - update TicketEvent ABI"
          git push
