name: Build | Ethereum | TickenEvent
on:
  push:
    branches:
      - main
    paths:
      - "ethereum/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18"

      - name: Install Dependencies
        working-directory: ./ethereum
        run: npm install

      - name: Build Smart Contract
        working-directory: ./ethereum
        run: npm run build

      - name: Update PUBBC Connector
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://${GITHUB_TOKEN}:x-oauth-basic@github.com/ticken-ts/ticken-pubbc-connector


          mv -f \
            ./ethereum/build/contracts/TickenEvent.json \
            ./ticken-pubbc-connector/eth-connector/TickenEvent.json

          cd ticken-pubbc-connector
          git config user.name "facundotorraca"
          git config user.email "ftorraca@fi.uba.ar"

          git add ./eth-connector/TickenEvent.json
          git commit -m "automatic ticket commit - update TicketEvent ABI"

          git push

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: eth-ticken-event
          path: ./ethereum/build/contracts/TickenEvent.json
