name: Build | Ethereum | TickenEvent
on:
  push:
    branches:
      - main
    paths:
      - "ethereum/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18"

      - name: Install Dependencies
        working-directory: ./ethereum
        run: npm install

      - name: Build Smart Contract
        working-directory: ./ethereum
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: eth-ticken-event
          path: ./ethereum/build/contracts/TickenEvent.json

      - name: "Checkout PUBBC Connector"
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ticken-ts/ticken-pubbc-connector
          path: ticken-pubbc-connector

      - name: Copy Contract ABI to Repository
        run: |
          rm ./eth-connector/TickenEvent.json
          cp ./ethereum/build/contracts/TickenEvent.json ./eth-connector/TickenEvent.json
          git add ./eth-connector/TickenEvent.json
          git commit -m "automatic ticket commit - update TicketEvent ABI"
          git pus
